value: dict
     | list
     | STRING
     | NUMBER
     | "true" | "false" | "null"
list : "[" [value ("," value)*] "]"
dict : "{" [pair ("," pair)*] "}"
pair : STRING ":" value

// break

paragraph: sentence+
sentence: word+ PUNCTUATION


PUNCTUATION: "," | "." | "!" | "?"

LCASE_LETTER: "a".."z"
UCASE_LETTER: "A".."Z"

LETTER: UCASE_LETTER | LCASE_LETTER
WORD: LETTER+


%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS